---
- hosts: all
  tasks:
    # - file: src={{ curdir }}/files/sshrc dest=~/.sshrc state=link
    - file: src={{ curdir }}/files/tmux.conf dest=~/.tmux.conf state=link force=true
    - file: src={{ curdir }}/files/skhdrc dest=~/.skhdrc state=link force=true
    - file: src={{ curdir }}/files/yabairc dest=~/.yabairc state=link force=true
    - file: src={{ curdir }}/files/gitconfig dest=~/.gitconfig state=link force=true
    - file: src={{ curdir }}/files/gitignore dest=~/.gitignore state=link force=true

    - name: Create ~/.zsh.after
      file: path=~/.zsh.after state=directory

    - file: src={{ curdir }}/files/zsh/aliases.zsh dest=~/.zsh.after/aliases.zsh state=link force=true
    - file: src={{ curdir }}/files/zshrc dest=~/.zshrc state=link force=true
