---
- hosts: all
  tasks:
    - file: src={{ curdir }}/files/sshrc dest=~/.sshrc state=link
    - file: src={{ curdir }}/files/tmux.conf dest=~/.tmux.conf state=link force=true

    - name: Create ~/.sshrc.d
      file: path=~/.sshrc.d state=directory

    - file: src={{ curdir }}/files/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - LS_COLORS
