---
- hosts: all
  tasks:
    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim

    - command: vim +PluginInstall +qall

    - command: ~/.vim/bundle/YouCompleteMe/install.py
      tags: ycm
