#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar                 off:45:0
yabai -m config mouse_follows_focus          off #on
yabai -m config focus_follows_mouse          off #autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.85
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# mission-control desktop labels

yabai -m query --spaces | jq -re 'map(.index) | reverse | .[] ' | xargs -I % sh -c 'yabai -m space % --destroy'

yabai -m space 1 --label code
rename_space 1 code

yabai -m space --create
yabai -m space 2 --label web
rename_space 2 web

yabai -m space --create
yabai -m space 3 --label mail
rename_space 3 mail

yabai -m space --create
yabai -m space 4 --label spotify
rename_space 4 spotify

yabai -m space --create
yabai -m space 5 --label notes
rename_space 5 notes

yabai -m space --create
yabai -m space 6 --label telegram
rename_space 6 telegram

yabai -m space --create
yabai -m space 7 --label skype
rename_space 7 skype

yabai -m space --create
yabai -m space 8 --label slack
rename_space 8 slack

yabai -m space --create
yabai -m space 9 --label misc
rename_space 9 misc


# specific space settings
yabai -m config --space mail  layout        stack

# window rules
yabai -m rule --add app="^iTerm2$" space=code
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app=".*Chrome.*" space=web
yabai -m rule --add app="^Arc$" space=web
yabai -m rule --add app=".*Firefox.*" space=web
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^Obsidian$" space=notes
yabai -m rule --add app="Toggl.*" space=misc
yabai -m rule --add app="^Transmission$" space=misc
yabai -m rule --add app="^Spotify$" space=spotify
yabai -m rule --add app="^Slack$" space=slack #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app="^Telegram$" space=telegram #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app="^Skype$" space=skype #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app=".*zoom.*" space=misc #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app="^.*Tunnel.*$" space=misc
yabai -m rule --add app="^.*VPN.*$" space=misc

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="1Password" app="^1Password$" manage=off
yabai -m rule --add label="Around" app="^Around$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
# yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
# yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# sketchybar
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Clean up empty spaces with no windows on them.
# yabai -m signal --add event=space_changed action="sh ~/.yabai/cleanEmptySpaces.sh"

~/.yabai/cleanEmptySpaces.sh

# Status bar (simple-bar)
yabai -m config external_bar all:28:0

# yabai -m query --spaces --display | \
#      jq -re 'map(select(."native-fullscreen" == 0)) | length > 1' \
#      && yabai -m query --spaces | \
#           jq -re 'map(select(."windows" == [] and ."focused" == 0).index) | reverse | .[] ' | \
#           xargs -I % sh -c 'yabai -m space % --destroy'
#
# yabai -m query --spaces | jq -re 'map(.index) | reverse | .[] ' | xargs -I % sh -c 'yabai -m space % --destroy'

borders active_color=0xff80eb34 inactive_color=0xff414550 width=6.0 blacklist="iTerm2,krisp" &

echo "yabai configuration loaded.."
