#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar                 all:40:0
yabai -m config mouse_follows_focus          off #on
yabai -m config focus_follows_mouse          off #autoraise
yabai -m config window_placement             second_child
# yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.85
yabai -m config window_border                off
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# mission-control desktop labels

yabai -m space 1 --label code

yabai -m space --create
yabai -m space 2 --label web

yabai -m space --create
yabai -m space 3 --label mail

yabai -m space --create
yabai -m space 4 --label notes

yabai -m space --create
yabai -m space 5 --label spotify

yabai -m space --create
yabai -m space 6 --label telegram

yabai -m space --create
yabai -m space 7 --label teams

yabai -m space --create
yabai -m space 8 --label slack

yabai -m space --create
yabai -m space 9 --label misc


# specific space settings
yabai -m config --space mail  layout        stack

# window rules
yabai -m rule --add app="^iTerm2$" space=code
yabai -m rule --add app="^Alacritty$" space=code
yabai -m rule --add app="^Wezterm$" space=code
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app=".*Chrome.*" space=code
yabai -m rule --add app="^Arc$" manage=on
yabai -m rule --add app="^Arc$" space=web
yabai -m rule --add app=".*Firefox.*" space=web
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^Obsidian$" space=notes
yabai -m rule --add app="Toggl.*" space=misc
yabai -m rule --add app="^Transmission$" space=misc
yabai -m rule --add app="^Spotify$" space=spotify
yabai -m rule --add app="^Slack$" space=slack #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app="^Telegram$" space=telegram #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app=".*Teams.*" space=misc #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app=".*zoom.*" space=misc #grid=1:1:0:0:1:1 #manage=off
yabai -m rule --add app="^.*Tunnel.*$" space=misc
yabai -m rule --add app="^.*VPN.*$" space=misc

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="1Password" app="^1Password$" manage=off
yabai -m rule --add label="eqMac" app="^eqMac$" manage=off

yabai -m rule --apply

echo "yabai configuration loaded.."
