export GREP_OPTIONS="--color=auto"

if [[ -x /opt/homebrew/bin/brew ]]; then
 eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
 eval "$(/usr/local/bin/brew shellenv)"
fi

export PATH="$HOME/bin:$PATH"

libpq_prefix=$(brew --prefix libpq 2>/dev/null)
if [[ -n "$libpq_prefix" ]]; then
 export PATH="$libpq_prefix/bin:$PATH"
fi
unset libpq_prefix

# zmodload zsh/zprof

zvm_config() {
 # Retrieve default cursor styles
 local ncur=$(zvm_cursor_style $ZVM_NORMAL_MODE_CURSOR)
 local icur=$(zvm_cursor_style $ZVM_INSERT_MODE_CURSOR)

 ZVM_NORMAL_MODE_CURSOR=$ncur'\e\e]12;#008800\a'
}

# Path to your oh-my-zsh installation.
# export ZSH=$HOME/.oh-my-zsh
DEFAULT_USER="accessd"

# Set name of the theme to load
# ZSH_THEME="dracula"

plugins=(
 # git
 # zsh-completions
 # zsh-vi-mode
 # zsh-autosuggestions
 # zsh-syntax-highlighting
)

# source $ZSH/oh-my-zsh.sh

# User configuration
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

export PYENV_ROOT="$HOME/.pyenv"
export PYENV_SHELL="zsh"
export TERM="xterm-256color"

# No duplicate history when reverse-searching my commands
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Load any custom after code
if [ -d $HOME/.zsh.after/ ]; then
 if [ "$(ls -A $HOME/.zsh.after/)" ]; then
   for config_file ($HOME/.zsh.after/*.zsh) source $config_file
 fi
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#export SSL_CERT_FILE=/etc/ssl/cert.pem

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#33859d,bold"

printf "\e[?1042l"

# PROMPT='%f%F{43}la%f%F{44}pt%f%F{38}op%f%F{44}:%1~/%f %F{44}%#%f '

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# https://github.com/agkozak/zsh-z
[ -f "$HOME/bin/zsh-z.plugin.zsh" ] && source "$HOME/bin/zsh-z.plugin.zsh"

autoload -U compinit; compinit
zstyle ':completion:*' menu select

# source ~/bin/tmuxinator.zsh

bindkey -v

bindkey "^A"   beginning-of-line                    # ctrl-a
bindkey "^B"   backward-char                        # ctrl-b
bindkey "^E"   end-of-line                          # ctrl-e
bindkey "^D"   delete-char                          # ctrl-d
bindkey "^K"   kill-line                            # ctrl-k
bindkey "^N"   down-line-or-search                  # ctrl-n
bindkey "^P"   up-line-or-search                    # ctrl-p
bindkey "^R"   history-incremental-search-backward  # ctrl-r
bindkey "^[[B" history-search-forward               # down arrow
bindkey "^[[A" history-search-backward              # up arrow

set -o vi
export EDITOR=nvim
export VISUAL=nvim

eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
eval "$(mise activate zsh)"
eval "$(atuin init zsh)"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/bin/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/bin/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/bin/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/bin/google-cloud-sdk/completion.zsh.inc"; fi

# slag
export PATH="$HOME/.slag/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
